struct Constants {
    // text
    static let welcomeTitle = "Добро пожаловать"
    static let welcomeSubtitle = "Ваше новое пространство для идей и задач"
    static let syncTitle = "Синхронизация в реальном времени"
    static let syncDescription = "Данные доступны мгновенно на любом устройстве"
    static let securityNote = "Ваши проекты под защитой Firebase Authentication"
    static let getStarted = "Get Started"
    static let errorMessage = "Заполните все поля"
    static let login = "Авторизуйтесь"
    static let emailAndPassword = "Email и пароль"
    static let google = "Google"
    static let appleID = "Apple ID"
    static let signUp = "Зарегистрироваться"
    static let signInWithAppleID = "Вход через Apple ID"
    static let continuee = "Продолжить"
    static let createAccount = "Создать аккаунт"
    static let signIn = "Вход в систему"
    static let signUpButton = "Зарегистрироваться"
    static let LogIn = "Войти"
    static let signInPrompt = "Уже есть аккаунт? Войти"
    static let signUpPrompt = "Нет аккаунта? Зарегистрироваться"
    static let signUpTitle = "Регистрация"
    static let signInTitle = "Авторизация"
    static let googleTitle = "Вход через Google"
    static let continueButton = "Продолжить"
    static let navigationTitle = "Google"
    static let successTitle = "Вы успешно вошли!"
    static let logoutButton = "Выйти в меню регистрации"
    static let navigationTitleEmail = "Главная"
    
    // image
    static let buttonOnboardingImage = "iphone.gen1.and.arrow.left"
    static let chevronRight = "chevron.right"
    static let envelopeFill = "envelope.fill"
    static let gCircleFill = "g.circle.fill"
    static let appleLogo = "apple.logo"
    
    // userDefaults
    static let userDefaults = "isLogin"
}
